### ISSUE TITLE
Can't use 'objectOrNull' as callback.

### ISSUE THREAD

**Issue by iyegoroff** [LabEG/is.ts#1]
This `is.every([{}], is.objectOrNull)` will crash, however this `is.every([{}], x => is.objectOrNull(x))` will work as expected.

**Comment by LabEG** [comment]
Fix all base type checking, for him you can write just `is.every([{}], is.objectOrNull)` or `is.every([{}], x => is.objectOrNull(x))`, both variants work correct.
For all others you must use only `is.every([{}], x => is.objectOrNull(x))` variant, because if remove `this` in others methods, then it will cause code bloat.
